name: format-check
on:
  pull_request:
    branches: [ "main" ]
jobs:
  csharp-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet tool restore
      - run: dotnet csharpier check .
